<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>

        //-----includes   indexOf
        const hero = ['诸葛亮', '小乔', '铠'];
        console.log(hero.includes('诸葛亮'));
        console.log(hero.includes('张飞'));




        //-----  **
        console.log(2 ** 10);
        console.log(Math.pow(2, 10));


        //-----async await


        const p = new Promise((resolve, reject) => {
            reject("失败!");
        })

        //await要放在async函数中 是指Promise对象返回的值“失败！”
        async function main() {
            try {
                let result = await p;
                console.log(result);
            } catch (e) {
                console.log(e);
            }
        }

        main();

        //-----rest
        //ES9中为对象提供了像数组一样的rest参数和扩展运算符

        function connect({ host, port, ...user }) {
            console.log(host);
            console.log(port);
            console.log(user);
        }

        connect({
            host: '127.0.0.1',
            port: 8080,
            username: 'root',
            password: '123',
            type: 'boss'
        })




        //-----正则命名分组

        let str = '<a href="https://www.baidu.com">百度</a>';
        const reg = /<a href="(?<url>.*)">(?<text>.*)<\/a>/;
        const result = reg.exec(str);
        console.log(result);
        console.log(result.groups.url);

    </script>
</body>

</html>